<?php
require '../include/connection.php';
date_default_timezone_set('Asia/Kolkata');
// $currentdate = date('d-m-Y h:i:s A', time());
$currentdate = date('d-m-Y');
$currentTime = date('h:i:s A', time());

?>
<?php
echo '<script>window.print();</script>';

?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=, initial-scale=1.0">
    <title>Customer Report</title>
    <style>
        table,
        td,
        th {
            border: 1px solid #ddd;
            text-align: center;
        }

        table {
            border-collapse: collapse;
            width: 100%;
        }

        th {
            padding: 5px;
        }

        .heading {
            color: black;
            font-weight: bolder;
            text-align: center;
            font-size: 40px;
        }

        .pdate {
            text-align: right;
        }

        @media print{
            .print-container{
                visibility: hidden;
            }
        }
    </style>
</head>

<body>
    <div class=print-container>



        <p class="heading">
            Footwear Shop Management System
        </p>
        <!-- <p>This Report Generated by the Admin.</p> -->

        <p class="pdate">Date : &nbsp;<?php echo $currentdate; ?></p>
        <p class="pdate">Time :&nbsp;<?php echo $currentTime; ?></p>
        <u>
            <h2 style="text-align: center;">Report of Customers</h2>
        </u>

        <table>
            <thead>
                <tr>
                    <th>No</th>
                    <th>Name </th>
                    <th>Email</th>
                    <th>Contact No</th>
                    <th>Gender</th>
                    <th>City</th>
                    <th>Created On</th>
                </tr>
            </thead>
            <?php

            $i = 0;
            $query = $conn->query("SELECT * FROM `tbluser` where role='customer'");

            ?>
            <tbody>
                <?php
                while ($fetch = $query->fetch_array()) {
                    $i++;

                ?>

                    <td>

                        <P><?php echo $i; ?></P>
                    </td>



                    <td>
                        <P><?php echo $fetch['fullname']; ?></P>
                    </td>

                    <td>
                        <P><?php echo $fetch['email']; ?></P>
                    </td>


                    <td>
                        <P>+91 <?php echo $fetch['contact_no']; ?></P>
                    </td>

                    <td>
                        <P><?php echo $fetch['gender']; ?></P>
                    </td>

                    <?php
                    $cid = $fetch['cityid'];
                    $city_name = "SELECT * FROM tblcity WHERE id = $cid";
                    $city_result = $conn->query($city_name);
                    if (mysqli_num_rows($city_result) > 0) {
                        $city_row = mysqli_fetch_array($city_result);
                        $cname = $city_row["name"];
                    }
                    ?>
                    <td>
                        <P><?php echo $cname; ?></P>
                    </td>

                    <td>
                        <P><?php echo $fetch['joining_date']; ?></P>
                    </td>


                <?php
                }
                ?>
            </tbody>
        </table>
    </div>
</body>


</html>